/**
 * Known NetEase song IDs. Used as fallback when music-manifest.json
 * loses its data (which happens frequently due to VSCode reverting it).
 * Generated by: node scripts/fetchNeteaseIds.mjs
 */
export const KNOWN_IDS: Record<string, string> = {
  "神のまにまに": "32431066",
  "SLEEP": "2738885153",
  "Melody (Original mix)": "36921285",
  "Dancin (Krono Remix)": "439121233",
  "Travelers' encore": "1879098277",
  "III": "3947467",
  "Ferrari": "550936829",
  "海阔天空": "1357375695",
  "Hold On": "2064842045",
  "梦醒": "1395222212",
  "Mine (Illenium Remix)": "30780496",
  "4 Days": "1859277720",
  "Lose You Now": "1809169083",
  "Slow Down": "1958031039",
  "Payphone": "4172700",
  "So Far Away": "521416693",
  "Umbrella (Matte Remix)": "518904426",
  "Shadow Of The Sun (Adventure Club Remix)": "28411642",
  "Sinos De Natal": "3320179802",
  "Maybe": "1393412185",
  "Wasted (Nightcore) [Bass Boosted] (feat": "1968316652",
  "Bleeding Love": "1388433823",
  "Counting Stars": "26060065",
  "In The Shadow Of The Sun": "29412405",
  "Love Is Gone (Acoustic)": "2724994876",
  "247": "1480504807",
  "Something Just Like This": "461347998",
  "Undertale": "39227624",
  "Trouble I'm In": "29758362",
  "Lost Within The End": "2670833053",
  "告白气球（Cover）": "2716020167",
  "Lifeline": "38019092",
};
