import { Song } from "../types";
import { extractColors } from "./utils";

interface ManifestEntry {
  id: string;
  title: string;
  artist: string;
  filePath: string;
  lyricsPath?: string;
  ttmlPath?: string;
  yrcPath?: string;
  coverPath?: string;
  neteaseId?: string;
}

const baseUrl = import.meta.env.BASE_URL ?? "/";
const normalizeBaseUrl = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;

const resolveAssetUrl = (filePath: string): string => {
  return `${normalizeBaseUrl}${filePath}`;
};

const fetchManifest = async (): Promise<ManifestEntry[]> => {
  const url = `${normalizeBaseUrl}music-manifest.json`;
  const response = await fetch(url);
  if (!response.ok) {
    console.warn(`Music manifest not found at ${url}, falling back to empty list`);
    return [];
  }
  return (await response.json()) as ManifestEntry[];
};

export const loadStaticSongs = async (): Promise<Song[]> => {
  const songs: Song[] = [];

  const manifest = await fetchManifest();
  if (!manifest.length) return songs;

  for (const item of manifest) {
    const fileUrl = resolveAssetUrl(item.filePath);
    let coverUrl: string | undefined;
    let colors: string[] = [];

    // Use build-time extracted cover image (generated by vite plugin)
    if (item.coverPath) {
      coverUrl = resolveAssetUrl(item.coverPath);
      try {
        colors = await extractColors(coverUrl);
      } catch (error) {
        console.warn("Failed to extract colors from cover:", item.title, error);
      }
    }

    // Load word-level lyrics — TTML (AMLL) or YRC (NetEase API)
    let lyrics: import("../types").LyricLine[] = [];
    let needsLyricsMatch = true;
    const { parseLyrics, isTtmlFormat } = await import("./lyrics");

    if (item.yrcPath) {
      try {
        const url = resolveAssetUrl(item.yrcPath);
        const res = await fetch(url);
        if (res.ok) {
          const text = await res.text();
          if (text.trim()) {
            const { parseNeteaseLyrics } = await import("./lyrics/netease");
            lyrics = parseNeteaseLyrics(text);
            needsLyricsMatch = false;
            console.log(`[Static] YRC: ${item.title} (${lyrics.length} lines)`);
          }
        }
      } catch { /* unavailable */ }
    }

    if (lyrics.length === 0 && item.ttmlPath) {
      try {
        const url = resolveAssetUrl(item.ttmlPath);
        const res = await fetch(url);
        if (res.ok) {
          const text = await res.text();
          if (text.trim() && isTtmlFormat(text)) {
            lyrics = parseLyrics(text);
            needsLyricsMatch = false;
            console.log(`[Static] TTML: ${item.title} (${lyrics.length} lines)`);
          }
        }
      } catch { /* unavailable */ }
    }

    const hasNeteaseId = item.neteaseId && item.neteaseId.trim().length > 0;
    songs.push({
      id: item.id,
      title: item.title,
      artist: item.artist,
      fileUrl,
      origin: fileUrl,
      source: "remote",
      coverUrl,
      lyrics,
      needsLyricsMatch,
      isNetease: hasNeteaseId || undefined,
      neteaseId: hasNeteaseId ? item.neteaseId : undefined,
      colors: colors.length > 0 ? colors : [],
    });
  }

  return songs;
};
