import { Song } from "../types";
import { parseLyrics } from "./lyrics";
import { extractColors } from "./utils";
import { fetchLyricsWithCache } from "./cache";

interface ManifestEntry {
  id: string;
  title: string;
  artist: string;
  filePath: string;
  lyricsPath?: string;
  coverPath?: string;
}

const baseUrl = import.meta.env.BASE_URL ?? "/";
const normalizeBaseUrl = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;

const resolveAssetUrl = (filePath: string): string => {
  return `${normalizeBaseUrl}${filePath}`;
};

const fetchManifest = async (): Promise<ManifestEntry[]> => {
  // Fetch music-manifest.json at runtime — this file is generated by the
  // Vite plugin at build time and sits next to index.html.  In dev mode the
  // plugin watches public/music/ and regenerates the manifest on changes so
  // a page refresh always reflects the latest files without a full rebuild.
  const url = `${normalizeBaseUrl}music-manifest.json`;
  const response = await fetch(url);
  if (!response.ok) {
    console.warn(`Music manifest not found at ${url}, falling back to empty list`);
    return [];
  }
  return (await response.json()) as ManifestEntry[];
};

export const loadStaticSongs = async (): Promise<Song[]> => {
  const songs: Song[] = [];

  const manifest = await fetchManifest();
  if (!manifest.length) return songs;

  for (const item of manifest) {
    const fileUrl = resolveAssetUrl(item.filePath);
    let lyrics;
    let needsLyricsMatch = true;
    let coverUrl: string | undefined;
    let colors: string[] = [];

    // Use build-time extracted cover image (generated by vite plugin)
    if (item.coverPath) {
      coverUrl = resolveAssetUrl(item.coverPath);
      try {
        colors = await extractColors(coverUrl);
      } catch (error) {
        console.warn("Failed to extract colors from cover:", item.title, error);
      }
    }

    if (item.lyricsPath) {
      try {
        const lyricsUrl = resolveAssetUrl(item.lyricsPath);
        const text = await fetchLyricsWithCache(lyricsUrl);
        if (text.trim().length > 0) {
          lyrics = parseLyrics(text);
          // Keep needsLyricsMatch = true so the app also attempts cloud
          // matching (NetEase → YRC / TTML).  Cloud data carries per-word
          // timing (逐字时间) that plain LRC files lack, enabling true
          // word-by-word fill animation.
          needsLyricsMatch = true;
        }
      } catch (error) {
        console.warn("Failed to load static lyrics file:", item.lyricsPath, error);
      }
    }

    songs.push({
      id: item.id,
      title: item.title,
      artist: item.artist,
      fileUrl,
      origin: fileUrl,
      source: "remote",
      coverUrl,
      lyrics,
      needsLyricsMatch,
      colors: colors.length > 0 ? colors : [],
    });
  }

  return songs;
};
